import Link from "next/link";
import { db } from "@/lib/db";
import { articles } from "@/lib/articles";
import { contactUrl, productQuoteUrl } from "@/lib/contact";

export const dynamic = "force-dynamic";

export default async function PublicHome() {
  const products = await db.product.findMany({ where: { active: true }, take: 3, orderBy: { name: "asc" } });
  const scheduleUrl = contactUrl("Hola, quiero información para agendar una primera valoración.", "Primera valoración");
  return <main><section className="hero"><div><p className="eyebrow">Fisioterapia veterinaria</p><h1>Movimiento con propósito. Seguimiento con evidencia.</h1><p className="hero-copy">Acompañamos la recuperación y movilidad de tu mascota con valoración funcional, ejercicio terapéutico y evolución documentada.</p><div className="actions"><a className="primary-button" href={scheduleUrl ?? "#contacto"}>Agendar valoración</a><Link className="secondary-button" href="/#primera-visita">Preparar mi visita</Link></div></div><div className="hero-mark" aria-hidden="true"><span>KV</span><small>movilidad · confort · progreso</small></div></section>
    <section className="public-section" id="servicios"><p className="eyebrow">Cómo ayudamos</p><h2>Atención enfocada en la función diaria</h2><div className="feature-grid"><article><strong>Valoración funcional</strong><p>Dolor, postura, marcha, fuerza y rango de movimiento registrados desde el inicio.</p></article><article><strong>Plan individual</strong><p>Ejercicios y modalidades seleccionados según diagnóstico, tolerancia y objetivos.</p></article><article><strong>Evolución medible</strong><p>Sesiones, dolor y ROM comparables para ajustar el protocolo con criterio clínico.</p></article></div></section>
    <section className="public-section visit-section" id="primera-visita"><div><p className="eyebrow">Primera valoración</p><h2>Qué traer</h2><ul><li>Diagnóstico o referencia veterinaria, si existe.</li><li>Radiografías, análisis y estudios previos.</li><li>Lista de medicamentos y suplementos actuales.</li><li>Videos de cómo camina o realiza actividades en casa.</li><li>Correa o arnés seguro y premios permitidos.</li></ul></div><div className="steps"><div><span>1</span><p><strong>Contáctanos</strong> para compartir el motivo de consulta.</p></div><div><span>2</span><p><strong>Confirmamos requisitos</strong> y disponibilidad.</p></div><div><span>3</span><p><strong>Valoramos y planeamos</strong> objetivos de tratamiento.</p></div></div></section>
    <section className="public-section"><div className="section-heading"><div><p className="eyebrow">Educación</p><h2>Entender también es cuidar</h2></div><Link href="/articles">Ver todos</Link></div><div className="article-grid">{articles.map((article) => <article className="public-card" key={article.slug}><span>Lectura breve</span><h3>{article.title}</h3><p>{article.summary}</p><Link href={`/articles/${article.slug}`}>Leer artículo →</Link></article>)}</div></section>
    <section className="public-section"><div className="section-heading"><div><p className="eyebrow">Productos</p><h2>Apoyo para la movilidad en casa</h2></div><Link href="/products">Ver catálogo</Link></div>{products.length ? <div className="product-grid">{products.map((product) => <article className="public-card product-card" key={product.id}>{product.imageUrl && <img src={product.imageUrl} alt={product.name} />}<h3>{product.name}</h3><p>{product.description}</p><strong>${product.price.toLocaleString("es-MX", { minimumFractionDigits: 2 })} MXN</strong>{productQuoteUrl(product.name) && <a className="secondary-button" href={productQuoteUrl(product.name)!}>Cotizar</a>}</article>)}</div> : <p className="muted">El catálogo se publicará próximamente.</p>}</section>
    <section className="contact-section" id="contacto"><p className="eyebrow">Agenda</p><h2>Cuéntanos qué necesita tu mascota</h2><p>Te orientaremos sobre la primera valoración y los estudios que conviene tener disponibles.</p>{scheduleUrl ? <a className="primary-button" href={scheduleUrl}>Solicitar información</a> : <p className="contact-missing">Configura el WhatsApp o correo de la clínica para activar solicitudes.</p>}</section>
  </main>;
}
